export const MOCK_DATA = [
  {
    id: 1,
    name: 'Chick Dahlen',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 2,
    name: 'Teddy Ketteringham',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 3,
    name: 'Pru Willowby',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 4,
    name: 'Minni Leverson',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 5,
    name: 'Goldina Brower',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 6,
    name: 'Jannelle Harpham',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 7,
    name: 'Deck Buntin',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 8,
    name: 'Letisha Rainsbury',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 9,
    name: 'Chrysler Schankel',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 10,
    name: 'Cherlyn Duiguid',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 11,
    name: 'Sim Chaffe',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 12,
    name: 'Adriana Wiffen',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 13,
    name: 'Field Ambrogelli',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 14,
    name: 'Sunny Kingsman',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 15,
    name: 'Ric Fussie',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 16,
    name: 'Coletta Coakley',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 17,
    name: 'Pris Farfoot',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 18,
    name: 'Halie Peddie',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 19,
    name: 'Sebastian Umfrey',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 20,
    name: 'Else MacNeilley',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 21,
    name: 'Nicko Daviot',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 22,
    name: 'Amber Schuricht',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 23,
    name: 'Delia McComb',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 24,
    name: 'Marven Pail',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 25,
    name: 'Adrianna Bendle',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 26,
    name: 'Ellissa Abrahamian',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 27,
    name: 'Alecia Saurat',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 28,
    name: 'Chevalier Podbury',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 29,
    name: 'Jeffy Garz',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 30,
    name: 'Aleda Dash',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 31,
    name: 'Lancelot Hedlestone',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 32,
    name: 'Harlene Valentin',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 33,
    name: 'Kai Croote',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 34,
    name: 'Alameda Kynvin',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 35,
    name: 'Calvin Woodrow',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 36,
    name: 'Alameda Goddard',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 37,
    name: 'Ginger Quarless',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 38,
    name: 'Iormina Siccombe',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 39,
    name: 'Lauren Geroldini',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 40,
    name: 'Hamel Busen',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 41,
    name: 'Hannie Macieja',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 42,
    name: 'Tuck Dennert',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 43,
    name: 'Karola Bellelli',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 44,
    name: 'Halsey Duligal',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 45,
    name: 'Giana Bianco',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 46,
    name: 'Sal Lokier',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 47,
    name: 'Wood Northing',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 48,
    name: 'Andris Towsie',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 49,
    name: 'Elset Townley',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 50,
    name: 'Eimile Kovalski',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 51,
    name: 'Cathlene Fowell',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 52,
    name: 'Loralee Luard',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 53,
    name: 'Zondra Jedraszczyk',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 54,
    name: 'Norah Espino',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 55,
    name: 'Rozella Blaymires',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 56,
    name: 'Lauritz Gain',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 57,
    name: 'Jonell Antoniottii',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 58,
    name: 'Hurlee Plaskitt',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 59,
    name: 'Sherye Osbidston',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 60,
    name: 'Rosana Haggith',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 61,
    name: 'Aubree Itzkowicz',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 62,
    name: 'Charmian McCritichie',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 63,
    name: "Haywood O'Lunny",
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 64,
    name: 'Arnoldo Penkman',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 65,
    name: 'Trixi Duchant',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 66,
    name: 'Rayner Edel',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 67,
    name: 'Marnie Bestwerthick',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 68,
    name: 'Stavro Northcote',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 69,
    name: 'Isiahi Lamberth',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 70,
    name: 'Randal Laxe',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 71,
    name: 'Basile Binge',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 72,
    name: 'Noreen Simounet',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 73,
    name: 'Clayborn Bigmore',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 74,
    name: 'Holly-anne Fydoe',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 75,
    name: 'Marisa Lyman',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 76,
    name: 'Hettie Little',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 77,
    name: 'Zulema Sarath',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 78,
    name: 'Julissa Bonafant',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 79,
    name: 'Janeczka Moorcroft',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 80,
    name: 'Merci Kerrigan',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 81,
    name: 'Cherlyn Perkins',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 82,
    name: 'Pennie Caps',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 83,
    name: 'Janetta Aronstam',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 84,
    name: 'Bobette Airdrie',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 85,
    name: 'Rich Heighton',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 86,
    name: 'Minor Timeby',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 87,
    name: 'Corette Leys',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 88,
    name: 'Arlinda Vergine',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 89,
    name: 'Juditha Waliszewski',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 90,
    name: 'Ignaz Arnull',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 91,
    name: 'Ethelred Jaggi',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 92,
    name: 'Elsy Kenefick',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 93,
    name: 'Lowrance Ambresin',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 94,
    name: 'Anjela Dunstone',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 95,
    name: 'Jenni Durman',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 96,
    name: 'Lonnard Crann',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 97,
    name: 'Mabel Pulham',
    target: 'Target 1234',
    status: false,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 98,
    name: 'Ricardo Branscomb',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 99,
    name: 'Myca Gradon',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
  {
    id: 100,
    name: 'Juliane Missington',
    target: 'Target 1234',
    status: true,
    last_scanned: '3 minutes ago',
    scans_per_hour: 42,
    last_7_days: 'chart',
  },
]
